### PR TITLE
Added Support for Decorators

### PR DESCRIPTION
**Pull request by pcasaes**
As with Interceptors the decorators can be loaded with AditionalClasses/Classpath

The relevant modification is on class org.jglue.cdiunit.internal.WeldTestUrlDeployment at lines 147-149.

Also added unit test.

### CODE REVIEW

**Comment by pcasaes** [comment]
I checkout at the original master (without the modifications) and ran the same test
mvn clean install -Dweld.test.version=2.3.4.Final

it gave the same error.

**Comment by seanf** [comment]
@pcasaes That failing test should be fixed by the various upgrades in https://github.com/BrynCooke/cdi-unit/pull/105

Can I get you to revert the re-ordering of imports in WeldTestUrlDeployment.java, please? Looks like there should just be one new import: `javax.decorator.Decorator`.

**Comment by pcasaes** [comment]
@seanf reverted the import order and placed the `javax.decorator.Decorator` import with the javax import block.

**Comment by seanf** [comment]
Trying to trigger a rebuild (and re-merge) in Travis...

**Comment by seanf** [comment]
Thanks for the pull request.

**Pull request merged**
